rest_routes:
    type: rest
    resource: "@RubyGarageRestBundle/Resources/config/routing.yml"

ruby_garage_project:
    resource: "@RubyGarageProjectBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@RubyGarageUserBundle/Controller/"
    type: annotation

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

main:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::index.html.twig'


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc